---

- name: install memcached
  homebrew: name={{ item }} state=latest
  with_items:
    - memcached

- name: check if memcached is loaded
  shell: brew services list | grep memcached
  changed_when: False
  register: memcached_loaded_result

- name: launch memcached
  shell: brew services start memcached
  when: "'started' not in memcached_loaded_result.stdout"
